# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_load', models.ImageField(upload_to='forum/static/upload')),
                ('picture_name', models.CharField(max_length=50)),
                ('picture_label', models.CharField(max_length=50)),
                ('picture_message', models.TextField(default=None)),
                ('picture_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', related_query_name='reply', to='forum.Picture'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
