# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170630_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_load',
            field=models.FileField(default='', upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_message',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
